name: YouTube Multi-Watcher v.1🔎📽️📼

on:
  workflow_dispatch:   # کرون‌جاب از همین طریق اجرایش می‌کند

permissions:
  contents: write

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install yt-dlp

      - name: Run scanner
        run: python run_checker.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}   # ✅ این را حتماً اضافه کن

      - name: Commit logs and cache
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update logs & cache & new_videos'
          file_pattern: 'logs/ cache/'
